AttackEfficiencyController.cpp.o: AttackEfficiencyController.cpp \
 $(INCLDIR)/AttackEfficiencyController.h \
 $(INCLDIR)/Attacker/Attacker.h \
 $(INCLDIR)/MemHandle/MemHandle.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/statistics.h \
 $(INCLDIR)/types.h \
 $(INCLDIR)/CLArgs.h \
 $(INCLDIR)/Victim/Victim.h \
 $(INCLDIR)/PlaintextKeyPairGenerator/PlaintextKeyPairGenerator.h \
 $(INCLDIR)/Attacker/EvictionAttacker.h \
 $(INCLDIR)/Attacker/Attacker.h \
 $(INCLDIR)/MMU/DirectMMU.h \
 $(INCLDIR)/MMU/MMU.h \
 $(INCLDIR)/MemArray.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/Random.h \
 $(INCLDIR)/Attacker/OccupancyAttacker.h \
 $(INCLDIR)/Attacker/SquareMultAttacker.h \
 $(INCLDIR)/Cache/SetAssocCache.h \
 $(INCLDIR)/Cache/AssocCache.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/Victim/AESVictim.h \
 $(INCLDIR)/Victim/BinaryVictim.h \
 $(INCLDIR)/Victim/SingleAccessVictim.h \
 $(INCLDIR)/Victim/SquareMultVictim.h \
 $(INCLDIR)/CacheFactory/CacheFactory.h \
 $(INCLDIR)/../pugixml/src/pugixml.hpp \
 $(INCLDIR)/../pugixml/src/pugiconfig.hpp
CacheContext.cpp.o: CacheContext.cpp \
 $(INCLDIR)/CacheContext.h
CacheFactory.cpp.o: CacheFactory.cpp \
 $(INCLDIR)/Cache/CEASERCache.h \
 $(INCLDIR)/Cache/SetAssocCache.h \
 $(INCLDIR)/Cache/AssocCache.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/statistics.h \
 $(INCLDIR)/types.h \
 $(INCLDIR)/Cache/CEASERSCache.h \
 $(INCLDIR)/Cache/CacheHierarchy.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/Cache/NewCache.h \
 $(INCLDIR)/CacheLine/CacheLine.h \
 $(INCLDIR)/Cache/PLcache.h \
 $(INCLDIR)/Cache/AssocCache.h \
 $(INCLDIR)/Cache/SetAssocCache.h \
 $(INCLDIR)/Cache/PhantomCache.h \
 $(INCLDIR)/Cache/ScatterCache.h \
 $(INCLDIR)/Cache/WayPartitionCache.h \
 $(INCLDIR)/Cache/DIPCache.h \
 $(INCLDIR)/Cache/DRRIPCache.h \
 $(INCLDIR)/CacheFactory/CacheFactory.h \
 $(INCLDIR)/../pugixml/src/pugixml.hpp \
 $(INCLDIR)/../pugixml/src/pugiconfig.hpp
clargs.cpp.o: clargs.cpp \
 $(INCLDIR)/CLArgs.h \
 $(INCLDIR)/Victim/Victim.h \
 $(INCLDIR)/types.h \
 $(INCLDIR)/PlaintextKeyPairGenerator/PlaintextKeyPairGenerator.h
Controller.cpp.o: Controller.cpp \
 $(INCLDIR)/Attacker/Attacker.h \
 $(INCLDIR)/MemHandle/MemHandle.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/statistics.h \
 $(INCLDIR)/types.h \
 $(INCLDIR)/CLArgs.h \
 $(INCLDIR)/Victim/Victim.h \
 $(INCLDIR)/PlaintextKeyPairGenerator/PlaintextKeyPairGenerator.h \
 $(INCLDIR)/Controller.h \
 $(INCLDIR)/MMU/DirectMMU.h \
 $(INCLDIR)/MMU/MMU.h \
 $(INCLDIR)/MemArray.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/Random.h \
 $(INCLDIR)/Attacker/EvictionAttacker.h \
 $(INCLDIR)/Attacker/Attacker.h \
 $(INCLDIR)/Attacker/OccupancyAttacker.h \
 $(INCLDIR)/Attacker/SquareMultAttacker.h \
 $(INCLDIR)/Cache/SetAssocCache.h \
 $(INCLDIR)/Cache/AssocCache.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/Victim/AESVictim.h \
 $(INCLDIR)/Victim/SquareMultVictim.h \
 $(INCLDIR)/CacheFactory/CacheFactory.h \
 $(INCLDIR)/../pugixml/src/pugixml.hpp \
 $(INCLDIR)/../pugixml/src/pugiconfig.hpp
EntropyLoss.cpp.o: EntropyLoss.cpp \
 $(INCLDIR)/Cache/CacheHierarchy.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/statistics.h \
 $(INCLDIR)/types.h \
 $(INCLDIR)/Cache/WayPartitionCache.h \
 $(INCLDIR)/Cache/SetAssocCache.h \
 $(INCLDIR)/Cache/AssocCache.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/CacheFactory/CacheFactory.h \
 $(INCLDIR)/../pugixml/src/pugixml.hpp \
 $(INCLDIR)/../pugixml/src/pugiconfig.hpp \
 $(INCLDIR)/EntropyLoss.h \
 $(INCLDIR)/MMU/DirectMMU.h \
 $(INCLDIR)/MMU/MMU.h \
 $(INCLDIR)/MemHandle/MemHandle.h \
 $(INCLDIR)/CLArgs.h \
 $(INCLDIR)/evaluation.h \
 $(INCLDIR)/Victim/SingleAccessVictim.h \
 $(INCLDIR)/Victim/Victim.h \
 $(INCLDIR)/PlaintextKeyPairGenerator/PlaintextKeyPairGenerator.h
main.cpp.o: main.cpp \
 $(INCLDIR)/AttackEfficiencyController.h \
 $(INCLDIR)/Attacker/Attacker.h \
 $(INCLDIR)/MemHandle/MemHandle.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/statistics.h \
 $(INCLDIR)/types.h \
 $(INCLDIR)/CLArgs.h \
 $(INCLDIR)/Victim/Victim.h \
 $(INCLDIR)/PlaintextKeyPairGenerator/PlaintextKeyPairGenerator.h \
 $(INCLDIR)/Attacker/EvictionAttacker.h \
 $(INCLDIR)/Attacker/Attacker.h \
 $(INCLDIR)/MMU/DirectMMU.h \
 $(INCLDIR)/MMU/MMU.h \
 $(INCLDIR)/CacheFactory/CacheFactory.h \
 $(INCLDIR)/../pugixml/src/pugixml.hpp \
 $(INCLDIR)/../pugixml/src/pugiconfig.hpp \
 $(INCLDIR)/Controller.h \
 $(INCLDIR)/EntropyLoss.h \
 $(INCLDIR)/evaluation.h \
 $(INCLDIR)/ProfilingEvaluation.h \
 $(INCLDIR)/Profiling/Profiling.h \
 $(INCLDIR)/Victim/SingleAccessVictim.h
ProfilingEvaluation.cpp.o: ProfilingEvaluation.cpp \
 $(INCLDIR)/Attacker/Attacker.h \
 $(INCLDIR)/MemHandle/MemHandle.h \
 $(INCLDIR)/Cache/Cache.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/statistics.h \
 $(INCLDIR)/types.h \
 $(INCLDIR)/CLArgs.h \
 $(INCLDIR)/Victim/Victim.h \
 $(INCLDIR)/PlaintextKeyPairGenerator/PlaintextKeyPairGenerator.h \
 $(INCLDIR)/MMU/MMU.h \
 $(INCLDIR)/MemArray.h \
 $(INCLDIR)/CacheContext.h \
 $(INCLDIR)/ProfilingEvaluation.h \
 $(INCLDIR)/Profiling/Profiling.h \
 $(INCLDIR)/Victim/SingleAccessVictim.h \
 $(INCLDIR)/evaluation.h \
 $(INCLDIR)/MMU/DirectMMU.h \
 $(INCLDIR)/Profiling/EvictionSetSizeProfiling.h \
 $(INCLDIR)/Profiling/FilledCacheProfiling/FilledCacheProfiling.h \
 $(INCLDIR)/Profiling/FilledCacheProfiling/FilledCacheProfilingGroupElim.h \
 $(INCLDIR)/Profiling/FilledCacheProfiling/FilledCacheProfiling.h \
 $(INCLDIR)/Profiling/FilledCacheProfiling/FilledCacheProfilingLRU.h \
 $(INCLDIR)/Profiling/FilledCacheProfiling/FilledCacheProfilingProbabilistic.h \
 $(INCLDIR)/Profiling/FilledCacheProfiling/FilledCacheProfilingSingleHold.h \
 $(INCLDIR)/Cache/CacheHierarchy.h \
 $(INCLDIR)/CacheFactory/CacheFactory.h \
 $(INCLDIR)/../pugixml/src/pugixml.hpp \
 $(INCLDIR)/../pugixml/src/pugiconfig.hpp
Random.cpp.o: Random.cpp \
 $(INCLDIR)/Random.h
